name: registro_de_ponto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqlite3: ^2.4.2
  sqflite: any
  intl: any
  calendar_date_picker2: ^0.5.5  
  flutter_launcher_icons: any
  csv: any
  path_provider: any
  permission_handler: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/gojo.png"